stages: 
 - build
 - test
 - deploy

 job-build:
 stage: build
 script:
  - echo "Building the application"

  job-test:
 stage: test
 script:
  - echo "testing the application"

  job-deploy:
 stage: deploy
 script:
  - echo "deploying the application"
